👷 Added tests back to pipeline (#48)
* Added tests back to pipeline

* tweak test command

* update test command to use the release configuration

* Update dotnet.yml

* 🐛 reverting changes

* downgraded global.json

* added test results output

* changed test reporter

* Changed build name

* changed test result file name

---------

Co-authored-by: Gordon Beeming <me@gordonbeeming.com>
Co-authored-by: Gordon Beeming <gordonbeeming@ssw.com.au>

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -11,6 +11,7 @@ on:
 
 jobs:
   build:
+    name: "Build" 
 
     runs-on: ubuntu-latest
 
@@ -22,5 +23,12 @@ jobs:
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore --configuration Release
-    # - name: Test
-    #   run: dotnet test --no-build --verbosity normal
+    - name: Test
+      run: dotnet test --no-build --no-restore --configuration Release --logger "trx;LogFileName=TestResults.trx"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Tests             # Name of the check run which will be created
+        path: "**/*.trx"        # Path to test results
+        reporter: dotnet-trx    # Format of test results
